# Generated by Django 5.0 on 2023-12-28 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorio',
            name='nome',
            field=models.CharField(blank=True, default='Laboratório', max_length=100, null=True),
        ),
    ]
