# Generated by Django 5.0 on 2024-02-27 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_laboratorio_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoDeServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=99, null=True)),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_de_servico', to='api.laboratorio')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=100, null=True)),
                ('metodo', models.CharField(blank=True, max_length=100, null=True)),
                ('cmc', models.CharField(blank=True, max_length=100, null=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='api.grupodeservico')),
            ],
        ),
    ]
